---
name: Build and Push Docker Image

'on':
  push:
    tags:
      - 'v*.*.*'  # Trigger only on semantic tags like v1.0.0

permissions:
  contents: write  # Required for checkout and creating releases

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod  # Run in prod environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version from tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            krelinga/video-in-be-stub:${{ env.TAG }}
            krelinga/video-in-be-stub:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: |
            Docker image for this release has been pushed to Docker Hub:
            - `krelinga/video-in-be-stub:${{ env.TAG }}`
            - `krelinga/video-in-be-stub:latest`
          make_latest: true